spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/grid_test_db
    username: postgres
    password: postgres
  jpa:
    show-sql: true
  properties:
    hibernate:
      format_sql: true

logging:
  level:
    root: INFO
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.jdbc.core.JdbcTemplate: trace
